/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ClasesLimite;

import ClasesControl.ControlSQL;
import ClasesEntidad.Marcaje;
import com.toedter.calendar.JDateChooser;
import java.util.ArrayList;
import java.util.Calendar;
import javax.swing.JOptionPane;

/**
 *
 * @author felipe
 */
public class PanelPrincipal extends javax.swing.JFrame {
    ControlSQL control = new ControlSQL();
    ArrayList <Marcaje> marcajes = new ArrayList();
    /**
     * Creates new form PanelPrincipal
     */
    public PanelPrincipal() {
        initComponents();
        inicializarPrograma();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        EnfermedadAnimalesCercanos = new javax.swing.JPopupMenu();
        tabbedPaneRound1 = new org.edisoncor.gui.tabbedPane.TabbedPaneRound();
        tabbedSelector21 = new org.edisoncor.gui.tabbedPane.TabbedSelector2();
        basicTableCellenderer1 = new org.edisoncor.gui.table.BasicTableCellenderer();
        panel22 = new org.edisoncor.gui.panel.Panel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Historia_Clinica = new org.edisoncor.gui.panel.Panel();
        panel24 = new org.edisoncor.gui.panel.Panel();
        fecha = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        Origen = new javax.swing.JComboBox();
        tipo_ingreso = new org.edisoncor.gui.textField.TextField();
        identificacion = new org.edisoncor.gui.textField.TextField();
        Sexo = new javax.swing.JComboBox();
        EDB = new javax.swing.JComboBox();
        Nombre_Comun = new org.edisoncor.gui.textField.TextField();
        genero = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        Especie = new javax.swing.JComboBox();
        buttonAction4 = new org.edisoncor.gui.button.ButtonAction();
        panel1 = new org.edisoncor.gui.panel.Panel();
        jScrollPane3 = new javax.swing.JScrollPane();
        Antecedentes = new javax.swing.JTextArea();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        panel2 = new org.edisoncor.gui.panel.Panel();
        marcaje = new org.edisoncor.gui.textField.TextField();
        jLabel13 = new javax.swing.JLabel();
        buttonAction5 = new org.edisoncor.gui.button.ButtonAction();
        nombreMarcaje = new javax.swing.JComboBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaMarcaje = new javax.swing.JTable();
        panel3 = new org.edisoncor.gui.panel.Panel();
        t_ambiental = new org.edisoncor.gui.textField.TextField();
        procedencia = new org.edisoncor.gui.textField.TextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        tiempo_cautiberio = new org.edisoncor.gui.textField.TextField();
        lugar_extraccion = new org.edisoncor.gui.textField.TextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        carac_cautiverio = new org.edisoncor.gui.textField.TextField();
        especia_contacto = new org.edisoncor.gui.textField.TextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        enfermedades_animales_cercanos = new org.edisoncor.gui.textField.TextField();
        humedad = new org.edisoncor.gui.textField.TextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        tiempo_transporte = new org.edisoncor.gui.textField.TextField();
        jLabel25 = new javax.swing.JLabel();
        tipo_transporte = new org.edisoncor.gui.textField.TextField();
        jLabel27 = new javax.swing.JLabel();
        tratamiento_previo = new org.edisoncor.gui.textField.TextField();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        panel4 = new org.edisoncor.gui.panel.Panel();
        consumo = new org.edisoncor.gui.textField.TextField();
        jLabel31 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        frecuencia = new org.edisoncor.gui.textField.TextField();
        jLabel29 = new javax.swing.JLabel();
        signos_Duracion = new org.edisoncor.gui.textField.TextField();
        dieta_sumunistrada = new org.edisoncor.gui.textField.TextField();

        EnfermedadAnimalesCercanos.setToolTipText("Enfermedad animales cercanos");
        EnfermedadAnimalesCercanos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        EnfermedadAnimalesCercanos.getAccessibleContext().setAccessibleName("Enfermedad animales cercanos");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabbedSelector21.addTab("Todas Las Historias", basicTableCellenderer1);

        Historia_Clinica.setColorPrimario(new java.awt.Color(254, 254, 254));
        Historia_Clinica.setColorSecundario(new java.awt.Color(254, 254, 254));

        panel24.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panel24.setColorPrimario(new java.awt.Color(254, 254, 254));
        panel24.setColorSecundario(new java.awt.Color(254, 254, 254));

        jLabel1.setBackground(new java.awt.Color(209, 209, 209));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(1, 1, 1));
        jLabel1.setText("Origen :");

        Origen.setEditable(true);
        Origen.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Nacimiento", "Cav", "Intercambio", "Abandono" }));
        Origen.setPreferredSize(new java.awt.Dimension(81, 20));

        identificacion.setPreferredSize(new java.awt.Dimension(81, 20));

        Sexo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Macho", "Hembra", "Indeterminado" }));
        Sexo.setPreferredSize(new java.awt.Dimension(81, 20));
        Sexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SexoActionPerformed(evt);
            }
        });

        EDB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Neonato", "Juvenil", "Sub Adulto", "Adulto", "Geriatrico" }));
        EDB.setPreferredSize(new java.awt.Dimension(81, 20));

        Nombre_Comun.setPreferredSize(new java.awt.Dimension(81, 20));

        genero.setEditable(true);
        genero.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Anfibios", "Aves", "Mamiferos", "Reptiles Crocodylus", "Reptiles Quelonios" }));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Genero:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Fecha:");

        jLabel4.setBackground(new java.awt.Color(209, 209, 209));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(1, 1, 1));
        jLabel4.setText("Identificacion");

        jLabel7.setBackground(new java.awt.Color(209, 209, 209));
        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(1, 1, 1));
        jLabel7.setText("Tipo Ingreso:");

        jLabel9.setBackground(new java.awt.Color(209, 209, 209));
        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(1, 1, 1));
        jLabel9.setText("Sexo:");

        jLabel10.setBackground(new java.awt.Color(209, 209, 209));
        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(1, 1, 1));
        jLabel10.setText("EDB:");

        jLabel11.setBackground(new java.awt.Color(209, 209, 209));
        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(1, 1, 1));
        jLabel11.setText("Nombre comun:");

        jLabel15.setBackground(new java.awt.Color(209, 209, 209));
        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(1, 1, 1));
        jLabel15.setText("Especie:");

        Especie.setEditable(true);
        Especie.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Aracnidos", "Insectos", "Vertebrados", "Aves", "Mamiferos", "Reptiles" }));

        javax.swing.GroupLayout panel24Layout = new javax.swing.GroupLayout(panel24);
        panel24.setLayout(panel24Layout);
        panel24Layout.setHorizontalGroup(
            panel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel24Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panel24Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(identificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel24Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel24Layout.createSequentialGroup()
                        .addGroup(panel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Origen, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(genero, 0, 160, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel24Layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Nombre_Comun, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26)
                .addGroup(panel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9)
                    .addComponent(jLabel15))
                .addGap(55, 55, 55)
                .addGroup(panel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(Especie, javax.swing.GroupLayout.Alignment.LEADING, 0, 160, Short.MAX_VALUE)
                    .addComponent(EDB, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tipo_ingreso, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Sexo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel24Layout.setVerticalGroup(
            panel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel24Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addGroup(panel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tipo_ingreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel24Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(panel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(genero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel10)))
                    .addComponent(EDB, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Origen, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel15)
                    .addComponent(Especie, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Sexo, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(Nombre_Comun, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(identificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addContainerGap())
        );

        buttonAction4.setText("Guardar");
        buttonAction4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAction4ActionPerformed(evt);
            }
        });

        panel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panel1.setColorPrimario(new java.awt.Color(254, 254, 254));
        panel1.setColorSecundario(new java.awt.Color(254, 254, 254));

        Antecedentes.setColumns(20);
        Antecedentes.setRows(5);
        jScrollPane3.setViewportView(Antecedentes);

        jLabel14.setBackground(new java.awt.Color(209, 209, 209));
        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(1, 1, 1));
        jLabel14.setText("Antecedentes:");

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane3))
                .addContainerGap())
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setText("HISTORIA CLINICA");

        panel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panel2.setColorPrimario(new java.awt.Color(254, 254, 254));
        panel2.setColorSecundario(new java.awt.Color(254, 254, 254));

        marcaje.setPreferredSize(new java.awt.Dimension(81, 20));
        marcaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                marcajeActionPerformed(evt);
            }
        });

        jLabel13.setBackground(new java.awt.Color(209, 209, 209));
        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(1, 1, 1));
        jLabel13.setText("Marcaje:");

        buttonAction5.setText("Agregar");
        buttonAction5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAction5ActionPerformed(evt);
            }
        });

        nombreMarcaje.setEditable(true);
        nombreMarcaje.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Chip", "Areta", "Corte", "Tatu", "Placa", "Marca", "Anillo" }));

        tablaMarcaje.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tablaMarcaje);

        javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
        panel2.setLayout(panel2Layout);
        panel2Layout.setHorizontalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addGap(100, 100, 100)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panel2Layout.createSequentialGroup()
                        .addComponent(nombreMarcaje, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(marcaje, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(66, 66, 66)
                .addComponent(buttonAction5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panel2Layout.setVerticalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(nombreMarcaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(marcaje, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonAction5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panel3.setColorPrimario(new java.awt.Color(254, 254, 254));
        panel3.setColorSecundario(new java.awt.Color(254, 254, 254));

        t_ambiental.setPreferredSize(new java.awt.Dimension(81, 20));
        t_ambiental.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_ambientalActionPerformed(evt);
            }
        });

        procedencia.setPreferredSize(new java.awt.Dimension(81, 20));

        jLabel17.setBackground(new java.awt.Color(209, 209, 209));
        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(1, 1, 1));
        jLabel17.setText("Procedencia");

        jLabel18.setBackground(new java.awt.Color(209, 209, 209));
        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(1, 1, 1));
        jLabel18.setText("T Ambiental          ");

        tiempo_cautiberio.setPreferredSize(new java.awt.Dimension(81, 20));
        tiempo_cautiberio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tiempo_cautiberioActionPerformed(evt);
            }
        });

        lugar_extraccion.setPreferredSize(new java.awt.Dimension(81, 20));
        lugar_extraccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lugar_extraccionActionPerformed(evt);
            }
        });

        jLabel19.setBackground(new java.awt.Color(209, 209, 209));
        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(1, 1, 1));
        jLabel19.setText("Lugar Extraccion");

        jLabel20.setBackground(new java.awt.Color(209, 209, 209));
        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(1, 1, 1));
        jLabel20.setText("Tiempo cautiverio");

        carac_cautiverio.setToolTipText("Características del cautiverio ");
        carac_cautiverio.setPreferredSize(new java.awt.Dimension(81, 20));
        carac_cautiverio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carac_cautiverioActionPerformed(evt);
            }
        });

        especia_contacto.setToolTipText("Especies con que ha estado en contacto  ");
        especia_contacto.setPreferredSize(new java.awt.Dimension(81, 20));

        jLabel21.setBackground(new java.awt.Color(209, 209, 209));
        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(1, 1, 1));
        jLabel21.setText("Especie Contacto");
        jLabel21.setToolTipText("Especies con que ha estado en contacto  ");

        jLabel22.setBackground(new java.awt.Color(209, 209, 209));
        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(1, 1, 1));
        jLabel22.setText("Carac Cautiverio");
        jLabel22.setToolTipText("Características del cautiverio ");

        enfermedades_animales_cercanos.setToolTipText("Enfermedades de animales cercanos  ");
        enfermedades_animales_cercanos.setPreferredSize(new java.awt.Dimension(81, 20));
        enfermedades_animales_cercanos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enfermedades_animales_cercanosActionPerformed(evt);
            }
        });

        humedad.setPreferredSize(new java.awt.Dimension(81, 20));
        humedad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                humedadActionPerformed(evt);
            }
        });

        jLabel23.setBackground(new java.awt.Color(209, 209, 209));
        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(1, 1, 1));
        jLabel23.setText("Humedad");

        jLabel24.setBackground(new java.awt.Color(209, 209, 209));
        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(1, 1, 1));
        jLabel24.setText("Enferm Anim Cerca");
        jLabel24.setToolTipText("Enfermedades de animales cercanos  ");
        jLabel24.setComponentPopupMenu(EnfermedadAnimalesCercanos);
        jLabel24.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        tiempo_transporte.setToolTipText("Tiempo de transporte ");
        tiempo_transporte.setPreferredSize(new java.awt.Dimension(81, 20));

        jLabel25.setBackground(new java.awt.Color(209, 209, 209));
        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(1, 1, 1));
        jLabel25.setText("Tiempo Transporte");
        jLabel25.setToolTipText("Tiempo de transporte ");

        tipo_transporte.setToolTipText("Tipo de transporte ");
        tipo_transporte.setPreferredSize(new java.awt.Dimension(81, 20));
        tipo_transporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipo_transporteActionPerformed(evt);
            }
        });

        jLabel27.setBackground(new java.awt.Color(209, 209, 209));
        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(1, 1, 1));
        jLabel27.setText("Tipo Transporte");
        jLabel27.setToolTipText("Tipo de transporte ");

        tratamiento_previo.setToolTipText("Tratamiento previo y Respuesta ");
        tratamiento_previo.setPreferredSize(new java.awt.Dimension(81, 20));
        tratamiento_previo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tratamiento_previoActionPerformed(evt);
            }
        });

        jLabel32.setBackground(new java.awt.Color(209, 209, 209));
        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(1, 1, 1));
        jLabel32.setText("Tratamiento Previo Respuesta");
        jLabel32.setToolTipText("Tratamiento previo y Respuesta ");

        jLabel33.setBackground(new java.awt.Color(209, 209, 209));
        jLabel33.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(1, 1, 1));
        jLabel33.setText("Anamnesicos");

        jLabel30.setBackground(new java.awt.Color(209, 209, 209));
        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(1, 1, 1));
        jLabel30.setText("%");

        jLabel34.setBackground(new java.awt.Color(209, 209, 209));
        jLabel34.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(1, 1, 1));
        jLabel34.setText("°C");

        panel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panel4.setColorPrimario(new java.awt.Color(254, 254, 254));
        panel4.setColorSecundario(new java.awt.Color(254, 254, 254));

        consumo.setPreferredSize(new java.awt.Dimension(81, 20));
        consumo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consumoActionPerformed(evt);
            }
        });

        jLabel31.setBackground(new java.awt.Color(209, 209, 209));
        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(1, 1, 1));
        jLabel31.setText("Consumo");

        jLabel26.setBackground(new java.awt.Color(209, 209, 209));
        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(1, 1, 1));
        jLabel26.setText("Frecuencia            ");

        jLabel28.setBackground(new java.awt.Color(209, 209, 209));
        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(1, 1, 1));
        jLabel28.setText("Dieta Suministrada");

        frecuencia.setPreferredSize(new java.awt.Dimension(81, 20));
        frecuencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frecuenciaActionPerformed(evt);
            }
        });

        jLabel29.setBackground(new java.awt.Color(209, 209, 209));
        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(1, 1, 1));
        jLabel29.setText("Signos Duracion");
        jLabel29.setToolTipText("Signos y duración ");

        signos_Duracion.setToolTipText("Signos y duración ");
        signos_Duracion.setPreferredSize(new java.awt.Dimension(81, 20));

        dieta_sumunistrada.setPreferredSize(new java.awt.Dimension(81, 20));
        dieta_sumunistrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dieta_sumunistradaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel4Layout = new javax.swing.GroupLayout(panel4);
        panel4.setLayout(panel4Layout);
        panel4Layout.setHorizontalGroup(
            panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel4Layout.createSequentialGroup()
                .addGroup(panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panel4Layout.createSequentialGroup()
                        .addComponent(jLabel31)
                        .addGap(120, 120, 120)
                        .addComponent(consumo, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel4Layout.createSequentialGroup()
                        .addComponent(jLabel28)
                        .addGap(47, 47, 47)
                        .addComponent(dieta_sumunistrada, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28)
                .addGroup(panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel4Layout.createSequentialGroup()
                        .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(frecuencia, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel4Layout.createSequentialGroup()
                        .addComponent(jLabel29)
                        .addGap(31, 31, 31)
                        .addComponent(signos_Duracion, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        panel4Layout.setVerticalGroup(
            panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dieta_sumunistrada, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(frecuencia, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28)
                    .addComponent(jLabel26))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(consumo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(signos_Duracion, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                    .addComponent(jLabel31)
                    .addComponent(jLabel29))
                .addContainerGap())
        );

        javax.swing.GroupLayout panel3Layout = new javax.swing.GroupLayout(panel3);
        panel3.setLayout(panel3Layout);
        panel3Layout.setHorizontalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel3Layout.createSequentialGroup()
                .addGap(307, 307, 307)
                .addComponent(jLabel33)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel3Layout.createSequentialGroup()
                        .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel3Layout.createSequentialGroup()
                                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(43, 43, 43)
                                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lugar_extraccion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tiempo_cautiberio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(panel3Layout.createSequentialGroup()
                                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel23, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(43, 43, 43)
                                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(panel3Layout.createSequentialGroup()
                                            .addComponent(humedad, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(0, 0, 0)
                                            .addComponent(jLabel30))
                                        .addComponent(enfermedades_animales_cercanos, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(tipo_transporte, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(26, 26, 26)
                        .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel3Layout.createSequentialGroup()
                                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE))
                                .addGap(24, 24, 24)
                                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(procedencia, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(panel3Layout.createSequentialGroup()
                                        .addComponent(t_ambiental, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, 0)
                                        .addComponent(jLabel34))))
                            .addGroup(panel3Layout.createSequentialGroup()
                                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                    .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel22, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(24, 24, 24)
                                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tiempo_transporte, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(especia_contacto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(carac_cautiverio, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(panel3Layout.createSequentialGroup()
                        .addComponent(jLabel32)
                        .addGap(18, 18, 18)
                        .addComponent(tratamiento_previo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel3Layout.setVerticalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel33)
                .addGap(18, 18, 18)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lugar_extraccion, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(procedencia, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                    .addComponent(jLabel19)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tiempo_cautiberio, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t_ambiental, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20)
                    .addComponent(jLabel18)
                    .addComponent(jLabel34))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(humedad, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(especia_contacto, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                    .addComponent(jLabel23)
                    .addComponent(jLabel21)
                    .addComponent(jLabel30))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enfermedades_animales_cercanos, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(carac_cautiverio, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24)
                    .addComponent(jLabel22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tipo_transporte, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tiempo_transporte, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                    .addComponent(jLabel27)
                    .addComponent(jLabel25))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(12, 12, 12)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tratamiento_previo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel32))
                .addContainerGap())
        );

        javax.swing.GroupLayout Historia_ClinicaLayout = new javax.swing.GroupLayout(Historia_Clinica);
        Historia_Clinica.setLayout(Historia_ClinicaLayout);
        Historia_ClinicaLayout.setHorizontalGroup(
            Historia_ClinicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Historia_ClinicaLayout.createSequentialGroup()
                .addGroup(Historia_ClinicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Historia_ClinicaLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(buttonAction4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(panel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel24, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(Historia_ClinicaLayout.createSequentialGroup()
                        .addGap(292, 292, 292)
                        .addComponent(jLabel16)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(panel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        Historia_ClinicaLayout.setVerticalGroup(
            Historia_ClinicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Historia_ClinicaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addGap(18, 18, 18)
                .addComponent(panel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonAction4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        jScrollPane1.setViewportView(Historia_Clinica);

        javax.swing.GroupLayout panel22Layout = new javax.swing.GroupLayout(panel22);
        panel22.setLayout(panel22Layout);
        panel22Layout.setHorizontalGroup(
            panel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 693, Short.MAX_VALUE)
        );
        panel22Layout.setVerticalGroup(
            panel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE)
        );

        tabbedSelector21.addTab("Nueva Historia", panel22);

        tabbedPaneRound1.addTab("tab1", tabbedSelector21);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tabbedPaneRound1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tabbedPaneRound1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void consumoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consumoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_consumoActionPerformed

    private void tratamiento_previoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tratamiento_previoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tratamiento_previoActionPerformed

    private void tipo_transporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipo_transporteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipo_transporteActionPerformed

    private void dieta_sumunistradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dieta_sumunistradaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dieta_sumunistradaActionPerformed

    private void frecuenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frecuenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_frecuenciaActionPerformed

    private void humedadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_humedadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_humedadActionPerformed

    private void enfermedades_animales_cercanosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enfermedades_animales_cercanosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enfermedades_animales_cercanosActionPerformed

    private void carac_cautiverioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carac_cautiverioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_carac_cautiverioActionPerformed

    private void lugar_extraccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lugar_extraccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lugar_extraccionActionPerformed

    private void tiempo_cautiberioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tiempo_cautiberioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tiempo_cautiberioActionPerformed

    private void t_ambientalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_ambientalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_ambientalActionPerformed

    private void buttonAction5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAction5ActionPerformed

        //  ArrayList <String> id_tipo_marcaje  = control.ejecutarConsultaFila("SELECT id_tipo_marcaje from tipo_marcaje");
        if(nombreMarcaje.getSelectedIndex()==0){
            JOptionPane.showMessageDialog(rootPane, "Al parecer no ha seleccionado ningun tipo de marcaje");
        }else{
            Marcaje marcaje = new Marcaje();
            if(this.marcaje.getText().length()==0){
                JOptionPane.showMessageDialog(rootPane, "Al parecer no ha ingresado nungun nombre de marcaje");
            }else{
                

                if(nombreMarcaje.getSelectedIndex()==-1 ){
                    Object objeto = control.ejecutarConsulta("SELECT nombre FROM tipo_marcaje WHERE nombre = '"+nombreMarcaje.getSelectedItem().toString()+"'");
                    if(objeto ==null){
                        marcaje.setId_marcaje(control.SiguienteID("tipo_marcaje"));
                        marcaje.setNombre_tipo_marcaje(nombreMarcaje.getSelectedItem().toString());
                        String[] vectorRegistros ={marcaje.getId_marcaje(),marcaje.getNombre_tipo_marcaje()};
                        if(!control.InsertarDatos(vectorRegistros, "tipo_marcaje")){
                            JOptionPane.showMessageDialog(rootPane, "Ops hubo un error al insertar este registro comprueba que todos los datos esten bien");
                        }
                    }
                    else{
                        JOptionPane.showMessageDialog(rootPane, "Por favor registre nuevamente: "+ nombreMarcaje.getSelectedItem().toString());
                    }
                }else{
                    marcaje.setId_marcaje(control.ejecutarConsulta("SELECT id_tipo_marcaje FROM tipo_marcaje WHERE nombre = '"+nombreMarcaje.getSelectedItem().toString()+"'")+"");
                    marcaje.setNombre_tipo_marcaje(nombreMarcaje.getSelectedItem().toString());

                }

                marcaje.setMarcaje(this.marcaje.getText());
                System.out.println(marcaje.getMarcaje());
                System.out.println(marcaje.getId_marcaje());
                System.out.println(marcaje.getNombre_tipo_marcaje());
                marcajes.add(marcaje);
                control.cargarBoxBox("tipo_marcaje", "nombre", nombreMarcaje);
                this.marcaje.setText("");
                tablaMarcaje.setModel(control.cargarTaablaMarcaje(marcajes));
            }

        }

    }//GEN-LAST:event_buttonAction5ActionPerformed

    private void marcajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_marcajeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_marcajeActionPerformed

    private void buttonAction4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAction4ActionPerformed
        // marcajes = new ArrayList<>();

        ArrayList<String>  campos = CapturaCamposHistoraClinica();
        System.out.println(campos);
        if(!control.InsertarDatos(campos, "historia_clinica")){
            JOptionPane.showMessageDialog(rootPane, "Oops al parecer los datos de historia clinica no se han guardado correctamente"
                + "\nintenta corregir los datos y prueba nuevamente");
//        }else{
//                  campos = capturarCamposAnamnesicos();
//                if(!control.InsertarDatos(campos, "anamnesicos")){
//                    JOptionPane.showMessageDialog(rootPane, "Oops al parecer los datos de Anamnesico no se han guardado correctamente"
//                   + "\nintenta corregir los datos y prueba nuevamente");
//                    //llenar campos de marcajes
//                    
//                    }
//                for (int i = 0; i < marcajes.size(); i++) {
//                        Marcaje marcaje = new Marcaje();
//                        marcaje = marcajes.get(i);
//                        String[] vecatorRegistros = {marcaje.getId_marcaje(),marcaje.getId_marcaje(),identificacion.getText()};
//                        if(!control.InsertarDatos(vecatorRegistros, "marcaje")){
//                            JOptionPane.showMessageDialog(rootPane, "Oops al parecer los datos de Marcaje no se han guardado correctamente"
//                                                                        + "\nintenta corregir los datos y prueba nuevamente");
//                        }
//        }
        }


        //      //  String[] contenidoCamposAnimal = contenidoCamposAnimal();
        //        boolean guardoExitoso = aceptar(panel21,null,"historia_clinica",campos);
        //        if (guardoExitoso) {
            //            System.out.println("exitoso");
            //        }
        //        else{
            //            System.out.println("negativo");
            //        }
        //        for (int i = 0; i < campos.size(); i++) {
            //            System.out.println(campos.get(i));
            //        }
    }//GEN-LAST:event_buttonAction4ActionPerformed

    private void SexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SexoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SexoActionPerformed

    public void inicializarPrograma(){
       control.cargarBoxBox("origen", "tipo_origen", Origen);
       control.cargarBoxBox("tipo_marcaje", "nombre", nombreMarcaje);
       control.cargarBoxBox("historia_clinica", "genero", genero);
       control.cargarBoxBox("historia_clinica", "especie", Especie);
       tablaMarcaje.setModel(control.cargarTaablaMarcaje(marcajes));
    }
    
    public String fecha(JDateChooser x){
    String fecha;
    int dia,mes,año;
    if(x.getCalendar() == null){
        return null;
    }else{
    dia=x.getCalendar().get(Calendar.DAY_OF_MONTH);
    mes=x.getCalendar().get(Calendar.MONTH)+1;
    año=x.getCalendar().get(Calendar.YEAR);
    fecha=String.valueOf(año)+"-"+String.valueOf(mes)+"-"+ String.valueOf(dia);
    
    return fecha;
    }
    }
    private boolean insertarDatosOrigen(String id_origen,String tipo_origen){
    boolean insertoConExito;
    String[] vectorRegistros = {id_origen,tipo_origen};
    insertoConExito = control.InsertarDatos(vectorRegistros, "origen");   
    
        return insertoConExito;
    }
    private <String> ArrayList capturarCamposAnamnesicos(){
     ArrayList <String> Captura  = new  ArrayList <> ();
    Captura.add((String)lugar_extraccion.getText());
    Captura.add((String)procedencia.getText());
    Captura.add((String)tiempo_cautiberio.getText());
    Captura.add((String)t_ambiental.getText());
    Captura.add((String)humedad.getText());
    Captura.add((String)especia_contacto.getText());
    Captura.add((String)enfermedades_animales_cercanos.getText());
    Captura.add((String)carac_cautiverio.getText());
    Captura.add((String)tipo_transporte.getText());
    Captura.add((String)tiempo_transporte.getText());
    Captura.add((String)dieta_sumunistrada.getText());
    Captura.add((String)frecuencia.getText());
    Captura.add((String)consumo.getText());
    Captura.add((String)signos_Duracion.getText());
    Captura.add((String)tratamiento_previo.getText());
    Captura.add((String)identificacion.getText());
     return Captura;
    }
    private <String> ArrayList CapturaCamposHistoraClinica(){
    ArrayList <String> Captura  = new  ArrayList <> ();
    Captura.add((String)fecha(fecha));
    Captura.add((String)tipo_ingreso.getText());
    Captura.add((String) genero.getSelectedItem().toString());
    Captura.add((String)EDB.getSelectedItem().toString());
    Object origen = (control.ejecutarConsulta("SELECT id_origen FROM origen WHERE tipo_origen = '"+Origen.getSelectedItem().toString()+"'"));
    
    if(origen == null){
        if(Origen.getSelectedItem().toString().length()==0){           
        //JOptionPane.showMessageDialog(rootPane, "Al parecer no ha ingresado ningun dato en el campo origen"); 
         Captura.add(null);
        }else{
            origen = control.SiguienteID("origen");
           if(!insertarDatosOrigen(""+origen,Origen.getSelectedItem().toString())){
               JOptionPane.showMessageDialog(rootPane, "Oops tal parece que el registro origen no se ha insertado con éxito");
               return null;
           }
        }
       
    }
    Captura.add((String) (origen+""));
    Captura.add((String) Especie.getSelectedItem().toString());
    Captura.add((String)Nombre_Comun.getText());
    Captura.add((String) Sexo.getSelectedItem());
    Captura.add((String)identificacion.getText());   
    return Captura;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PanelPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PanelPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PanelPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PanelPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PanelPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Antecedentes;
    private javax.swing.JComboBox EDB;
    private javax.swing.JPopupMenu EnfermedadAnimalesCercanos;
    private javax.swing.JComboBox Especie;
    private org.edisoncor.gui.panel.Panel Historia_Clinica;
    private org.edisoncor.gui.textField.TextField Nombre_Comun;
    private javax.swing.JComboBox Origen;
    private javax.swing.JComboBox Sexo;
    private org.edisoncor.gui.table.BasicTableCellenderer basicTableCellenderer1;
    private org.edisoncor.gui.button.ButtonAction buttonAction4;
    private org.edisoncor.gui.button.ButtonAction buttonAction5;
    private org.edisoncor.gui.textField.TextField carac_cautiverio;
    private org.edisoncor.gui.textField.TextField consumo;
    private org.edisoncor.gui.textField.TextField dieta_sumunistrada;
    private org.edisoncor.gui.textField.TextField enfermedades_animales_cercanos;
    private org.edisoncor.gui.textField.TextField especia_contacto;
    private com.toedter.calendar.JDateChooser fecha;
    private org.edisoncor.gui.textField.TextField frecuencia;
    private javax.swing.JComboBox genero;
    private org.edisoncor.gui.textField.TextField humedad;
    private org.edisoncor.gui.textField.TextField identificacion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private org.edisoncor.gui.textField.TextField lugar_extraccion;
    private org.edisoncor.gui.textField.TextField marcaje;
    private javax.swing.JComboBox nombreMarcaje;
    private org.edisoncor.gui.panel.Panel panel1;
    private org.edisoncor.gui.panel.Panel panel2;
    private org.edisoncor.gui.panel.Panel panel22;
    private org.edisoncor.gui.panel.Panel panel24;
    private org.edisoncor.gui.panel.Panel panel3;
    private org.edisoncor.gui.panel.Panel panel4;
    private org.edisoncor.gui.textField.TextField procedencia;
    private org.edisoncor.gui.textField.TextField signos_Duracion;
    private org.edisoncor.gui.textField.TextField t_ambiental;
    private org.edisoncor.gui.tabbedPane.TabbedPaneRound tabbedPaneRound1;
    private org.edisoncor.gui.tabbedPane.TabbedSelector2 tabbedSelector21;
    private javax.swing.JTable tablaMarcaje;
    private org.edisoncor.gui.textField.TextField tiempo_cautiberio;
    private org.edisoncor.gui.textField.TextField tiempo_transporte;
    private org.edisoncor.gui.textField.TextField tipo_ingreso;
    private org.edisoncor.gui.textField.TextField tipo_transporte;
    private org.edisoncor.gui.textField.TextField tratamiento_previo;
    // End of variables declaration//GEN-END:variables
}
